// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wntimswnxbbrqdwsscrs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndudGltc3dueGJicnFkd3NzY3JzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5MjIzMTcsImV4cCI6MjA2OTQ5ODMxN30.vNAdNQc7mdTFIEKtrE-xt9XQkniy3Yj0ZtGzc39uQOc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});